/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboards;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JScrollPane;
import org.swiftgantt.Config;
import org.swiftgantt.GanttChart;
import org.swiftgantt.model.GanttModel;
import org.swiftgantt.model.Task;
import org.swiftgantt.ui.TimeUnit;

import connector.JobDatabaseConnector;
import jobschedule.JobScheduler;

import java.text.*;
import java.time.LocalDateTime;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author jane
 */
public class jobsDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Inventory_tab
     */
    public jobsDashboard() {
        initComponents();
        
        gantt = new GanttChart();
        gantt.setTimeUnit(TimeUnit.Hour);
        startDate= LocalDateTime.now().plusDays(1);
        endDate= LocalDateTime.now().plusDays(7);
        
        koMonth = startDate.getMonthValue();
        koYear = startDate.getYear();
        koDate = startDate.getDayOfMonth();
        
        dlMonth= endDate.getMonthValue();
        dlYear = endDate.getYear();
        dlDate = endDate.getDayOfMonth();
        
        config = gantt.getConfig();
        config.setWorkingTimeBackColor(Color.YELLOW);//Set background color for working time.
        config.setTimeUnitWidth(100);//Set width for time unit
        config.setWorkingDaysSpanOfWeek(new int[]{Calendar.SUNDAY, Calendar.SATURDAY});//Set span of working days in each week
        config.setWorkingHoursSpanOfDay(new int[]{9,17});
        model = new GanttModel();
        model.setKickoffTime( new org.swiftgantt.common.Time(koYear, koMonth, koDate));
        model.setDeadline( new org.swiftgantt.common.Time(dlYear, dlMonth, dlDate));
        /*Task taskGroup = new Task("My Work 1", new org.swiftgantt.common.Time(2017, 10, 17), new org.swiftgantt.common.Time(2017, 10, 30));
        Task task1 = new Task("Sub-task 1", new org.swiftgantt.common.Time(2017, 10, 17), new org.swiftgantt.common.Time(2017, 10, 18));
        org.swiftgantt.model.Task task2 = new Task();
        task2.setName("Sub-task 2");
        task2.setStart(new org.swiftgantt.common.Time(2017, 10, 19));
        task2.setEnd(new org.swiftgantt.common.Time(2017, 10, 21));// Since version 0.3.0, the end time set to a task is included in duration of the task
        taskGroup.add(new org.swiftgantt.model.Task[]{task1, task2});
        task2.addPredecessor(task1);
        model.addTask(taskGroup);*/
        gantt.setModel(model);
        gantt.setVisible(true);
        
        populateGantt();
        
        chartPanel.setLayout(new GridLayout());
	chartPanel.add(gantt, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jList1 = new javax.swing.JList<>();
        jobsButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        backButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        addJobButton = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        Category = new javax.swing.JComboBox<>();
        allJobsTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jobDescription = new javax.swing.JScrollPane();
        refreshTable = new javax.swing.JButton();
        nextDate = new javax.swing.JButton();
        previousDate = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jobsButton.setText("JOBS");
        jobsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobsButtonMouseClicked(evt);
            }
        });
        jobsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsButtonActionPerformed(evt);
            }
        });

        inventoryButton.setText("INVENTORY");
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        customerButton.setText("CUSTOMERS");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });

        signoutButton.setText("SIGN OUT");
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK");

        addJobButton.setText("Add Job");

        searchInput.setText("[Enter text]");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        allJobsTable.setViewportView(jTable1);

        refreshTable.setText("Refresh");

        nextDate.setText("Next week");
        nextDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextDateButtonActionPerformed(evt);
            }
        });

        previousDate.setText("Last week");
        previousDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousDateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        
        JButton btnCurrentWeek = new JButton("Current Week");
        btnCurrentWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentWeekButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jobsButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        				.addComponent(inventoryButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        				.addComponent(customerButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        				.addComponent(signoutButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        				.addComponent(backButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(searchInput, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(Category, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(searchButton))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(6)
        							.addComponent(chartPanel, GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(previousDate, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(btnCurrentWeek)
        							.addGap(18)
        							.addComponent(nextDate, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)))
        					.addGap(171)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(refreshTable, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
        						.addComponent(allJobsTable, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        						.addComponent(jobDescription, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        						.addComponent(addJobButton, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))))
        			.addGap(25))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(60)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(previousDate)
        				.addComponent(btnCurrentWeek)
        				.addComponent(nextDate))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(chartPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jobsButton, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(inventoryButton, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(customerButton, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(signoutButton, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(backButton, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(allJobsTable, GroupLayout.PREFERRED_SIZE, 276, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jobDescription, GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(addJobButton)))
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(refreshTable)
        			.addGap(91)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(searchInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(searchButton)
        				.addComponent(Category, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jTextPane1 = new javax.swing.JTextPane();
        jobDescription.setViewportView(jTextPane1);
        
                jTextPane1.setText("<JobDescriptions>");
        getContentPane().setLayout(layout);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(screenSize.width, screenSize.height-100));
        setLocationRelativeTo(null);

    }// </editor-fold>//GEN-END:initComponents

    private void jobsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jobsButtonMouseClicked
    private void previousDateButtonActionPerformed(java.awt.event.ActionEvent evt){
    	deployPreviousDate();
    	gantt.setVisible(true);
    }
    private void nextDateButtonActionPerformed(java.awt.event.ActionEvent evt){
    	deployNextDate();
    	gantt.setVisible(true);
    }
    private void currentWeekButtonActionPerformed(java.awt.event.ActionEvent evt){
        gantt = new GanttChart();
        gantt.setTimeUnit(TimeUnit.Hour);
        startDate= LocalDateTime.now().plusDays(1);
        endDate= LocalDateTime.now().plusDays(7);
        
        koMonth = startDate.getMonthValue();
        koYear = startDate.getYear();
        koDate = startDate.getDayOfMonth();
        
        dlMonth= endDate.getMonthValue();
        dlYear = endDate.getYear();
        dlDate = endDate.getDayOfMonth();
        model.setKickoffTime( new org.swiftgantt.common.Time(koYear, koMonth, koDate));
        model.setDeadline( new org.swiftgantt.common.Time(dlYear, dlMonth, dlDate));
        
    }
    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        clientsDashboard clientsDash = new clientsDashboard();
        clientsDash.setVisible(true);
        dispose();
    }//GEN-LAST:event_customerButtonActionPerformed

    private void jobsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsButtonActionPerformed
        // TODO add your handling code here:
        jobsDashboard jobsDash = new jobsDashboard();
        jobsDash.setVisible(true);
        dispose();
    }//GEN-LAST:event_jobsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
        partsDashboard partsDash = new partsDashboard();
        partsDash.setVisible(true);
        dispose();
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
        // TODO add your handling code here:
        loginDashboard loginDash = new loginDashboard();
        loginDash.setVisible(true);
        dispose();
    }//GEN-LAST:event_signoutButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
                 
             
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jobsDashboard().setVisible(true);
            }
        });
    }
    
    private void deployPreviousDate(){
    	startDate = startDate.minusDays(7);
    	endDate = endDate.minusDays(7);
    	
        koMonth = startDate.getMonthValue();
        koYear = startDate.getYear();
        koDate = startDate.getDayOfMonth();
        
        dlMonth= endDate.getMonthValue();
        dlYear = endDate.getYear();
        dlDate = endDate.getDayOfMonth();
        
        model.setKickoffTime( new org.swiftgantt.common.Time(koYear, koMonth, koDate));
        model.setDeadline( new org.swiftgantt.common.Time(dlYear, dlMonth, dlDate));
    }
    private void deployNextDate(){
    	startDate = startDate.plusDays(7);
    	endDate = endDate.plusDays(7);
    	
        koMonth = startDate.getMonthValue();
        koYear = startDate.getYear();
        koDate = startDate.getDayOfMonth();
        
        dlMonth= endDate.getMonthValue();
        dlYear = endDate.getYear();
        dlDate = endDate.getDayOfMonth();
        
        model.setKickoffTime( new org.swiftgantt.common.Time(koYear, koMonth, koDate));
        model.setDeadline( new org.swiftgantt.common.Time(dlYear, dlMonth, dlDate));
    }
    private void populateGantt(){

        /*Task taskGroup = new Task("My Work 1", new org.swiftgantt.common.Time(2017, 10, 17), new org.swiftgantt.common.Time(2017, 10, 30));
        Task task1 = new Task("Sub-task 1", new org.swiftgantt.common.Time(2017, 10, 17), new org.swiftgantt.common.Time(2017, 10, 18));
        org.swiftgantt.model.Task task2 = new Task();
        task2.setName("Sub-task 2");
        task2.setStart(new org.swiftgantt.common.Time(2017, 10, 19));
        task2.setEnd(new org.swiftgantt.common.Time(2017, 10, 21));// Since version 0.3.0, the end time set to a task is included in duration of the task

        taskGroup.add(new org.swiftgantt.model.Task[]{task1, task2});

        task2.addPredecessor(task1);
        model.addTask(taskGroup);*/
        
        //add tasks
        JobScheduler js = new JobScheduler(startDate.toLocalDate());
        JobDatabaseConnector jdc = new JobDatabaseConnector();
        Task mechanicTaskGroups[] = new Task[5];
        for (int i = 0; i < mechanicTaskGroups.length; i++){
       	 mechanicTaskGroups[i] = new Task("Mechanic "+ (i+1), new org.swiftgantt.common.Time(koYear, koMonth, koDate), new org.swiftgantt.common.Time(dlYear, dlMonth, dlDate));
       	 ResultSet rs = jdc.findJob("mechanicID", "=", (i+1));
       	 try{
       		 Task predecessor = null;
       		 int iter = 0;
       		 while(rs.next()){
       			 Task job = new Task("Job: " + rs.getInt("jobID"), new org.swiftgantt.common.Time(rs.getTimestamp("jobStartDateHour")), new org.swiftgantt.common.Time(rs.getTime("jobEndDateHour")));
       			 mechanicTaskGroups[i].add(job);
       			 if(iter>0){
       				 mechanicTaskGroups[i].addPredecessor(predecessor);
       			 }
       			 predecessor = job;
       			 iter++;
       		 }
       	 }catch(Exception e){
       		 e.printStackTrace();
       	 }
       	 model.addTask(mechanicTaskGroups[i]);
        }
        
        gantt.setVisible(true);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JButton addJobButton;
    private javax.swing.JScrollPane allJobsTable;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JScrollPane jobDescription;
    private javax.swing.JButton jobsButton;
    private javax.swing.JButton nextDate;
    private javax.swing.JButton previousDate;
    private javax.swing.JButton refreshTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton signoutButton;
    
    private GanttChart gantt;
    private LocalDateTime startDate;
    private LocalDateTime endDate;
    
    int koMonth;
    int koYear;
    int koDate;
    
    int dlMonth;
    int dlYear;
    int dlDate;
    
    Config config;
    GanttModel model;
}